apiVersion: v1
kind: Service
metadata:
  name: myweb
  labels:
    app: myweb
spec:
  ports:
    - port: 80
      nodePort: 30105
  selector:
    app: myweb
    tier: frontend
  type: NodePort

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc1
  labels:
    app: myweb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: myweb
spec:
    selector:
          matchLabels:
              app: myweb
              tier: frontend

    template:
        metadata:
            name: myweb
            labels:
                app: myweb
                tier: frontend

        spec:
            containers:
                - name: myweb
                  image: rupali04/webserver:v1
                  volumeMounts: 
                      - name: web-vol1
                        mountPath: /var/www/html
            volumes:
                - name: web-vol1
                  persistentVolumeClaim: 
                      claimName: web-pvc1
